### ISSUE TITLE
incorrect hash 

### ISSUE THREAD

**Issue by dionevella** [BastianGschrey/PowerTune#49]
Error while compiling due to incorrect hash on some files as per image

![image](https://user-images.githubusercontent.com/65804119/82723752-89125780-9cd1-11ea-9beb-62d75111ac73.png)

can this be looked into please? 

regards
d

**Comment by sikrip** [comment]
I had this problem too.

I ended up building QT for pi and then building powertune.

**Comment by BastianGschrey** [comment]
This is a  check for the downloaded files. As the error message says:  "Incomplete download"
A retry will fix this issue as it restarts the download for all failed components.
