### ISSUE TITLE
Unable to compile - QT Error

### ISSUE THREAD

**Issue by cplagz** [BastianGschrey/PowerTune#50]
Have managed to get through a few other issues while compiling but this one has me stumped log below ;  any input appreciated.  Fresh Ubuntu 17.04 install

>>> powertune master Configuring
cd /home/cplagz/buildroot/output/build/powertune-master; PATH="/home/cplagz/buildroot/output/host/bin:/home/cplagz/buildroot/output/host/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin" /home/cplagz/buildroot/output/host/usr/bin/qmake
Info: creating stash file /home/cplagz/buildroot/output/build/powertune-master/.qmake.stash
Project ERROR: Unknown module(s) in QT: charts location positioning sensors multimedia
package/pkg-generic.mk:217: recipe for target '/home/cplagz/buildroot/output/build/powertune-master/.stamp_configured' failed
make[1]: *** [/home/cplagz/buildroot/output/build/powertune-master/.stamp_configured] Error 3
Makefile:79: recipe for target '_all' failed
make: *** [_all] Error 2

**Comment by cplagz** [comment]
abandoned

**Comment by pgrandin** [comment]
If anyone faces the same issue, you need to make sure that these options are set:
```
BR2_PACKAGE_QT5CHARTS=y
BR2_PACKAGE_QT5LOCATION=y
BR2_PACKAGE_QT5SENSORS=y
BR2_PACKAGE_QT5MULTIMEDIA=y
```
