### ISSUE TITLE
Autoconnect at startup 

### ISSUE THREAD

**Issue by MarkusIppy** [BastianGschrey/PowerTune#9]
Add autoconnect checkbox to serialsettings . 
Feature should work as follows 
- Permanently store selected ECU
- Permanently store selected COM Port
- Permanently store state of autoconnect checkbox 
- Check settings at startup and if autoconnect checkbox was ticket , connect automatically

**Comment by BastianGschrey** [comment]
Class QSettings should be used:
Wiki: https://wiki.qt.io/How_to_Use_QSettings

**Comment by MarkusIppy** [comment]
Created checkbox in SerialSettings.qml ( currently without function)

**Comment by MarkusIppy** [comment]
added autostart as non selectable default (currently commented) 
Uncomment SerialSettings line 11  to activate

**Comment by MarkusIppy** [comment]
Added evaluation of checkbox state and if enabled automatically connect with previous settings at startup
Component.onCompleted: if (connectAtStart.checkState == "2") Serial.openConnection(serialName.currentText, ecuSelect.currentIndex, interfaceSelect.currentIndex)
